#!/usr/bin/env python3
"""Per-Sub-Domain search keywords and snippet-classification vocabulary."""

from __future__ import annotations

# Qualifiers appended to every query to bias results toward the kind of page the
# mode wants: structured corpora for ``datasets``, readable prose for ``text``.
QUERY_QUALIFIER = "dataset OR github OR repository OR corpus"
TEXT_QUERY_QUALIFIER = "guide OR tutorial OR explained OR documentation OR writeup"

DOMAIN_KEYWORDS: dict[str, list[str]] = {
    "Application Security": [
        "vulnerable source code dataset",
        "secure code review dataset",
        "SAST static analysis labeled dataset",
        "OWASP code vulnerability dataset",
        "CWE annotated source code dataset",
        "software vulnerability commit dataset",
        "web application attack payload dataset",
        "code security bug dataset github",
    ],
    "Network Security": [
        "network intrusion detection dataset",
        "network traffic pcap labeled dataset",
        "IDS flow dataset cybersecurity",
        "DDoS attack network dataset",
        "botnet traffic dataset",
        "NetFlow anomaly detection dataset",
        "packet capture malware traffic dataset",
        "firewall log dataset",
    ],
    "Cloud Security": [
        "cloud security misconfiguration dataset",
        "kubernetes security dataset",
        "cloud CSPM findings dataset",
        "AWS Azure GCP security best practices dataset",
        "container image vulnerability dataset",
        "cloud audit log dataset security",
        "terraform IaC misconfiguration dataset",
        "S3 bucket exposure dataset",
    ],
    "Identity Access and Management": [
        "identity access management dataset",
        "authentication logs dataset security",
        "privileged access abuse dataset",
        "IAM policy misconfiguration dataset",
        "account takeover dataset",
        "OAuth SAML token dataset",
        "insider threat access dataset",
        "RBAC permissions dataset",
    ],
    "Incident Response and Forensics": [
        "digital forensics dataset",
        "incident response playbook dataset",
        "memory forensics dataset",
        "DFIR investigation dataset",
        "disk image forensic dataset",
        "Windows event log forensic dataset",
        "timeline analysis artifact dataset",
        "malware incident case dataset",
    ],
    "Data Security and Privacy": [
        "PII detection dataset",
        "data loss prevention dataset",
        "data privacy compliance dataset",
        "sensitive data classification dataset",
        "GDPR data subject dataset",
        "de-identification anonymization dataset",
        "data breach records dataset",
        "credential leak dataset",
    ],
    "Penetration Testing": [
        "penetration testing dataset",
        "exploit proof of concept dataset",
        "exploit database github",
        "red team TTP dataset",
        "web pentest report dataset",
        "privilege escalation technique dataset",
        "attack payload dataset",
        "CTF exploit writeup dataset",
    ],
    "Vulnerability Management": [
        "CVE vulnerability dataset",
        "CVSS scoring dataset",
        "vulnerability scan results dataset",
        "CWE weakness enumeration dataset",
        "patch management dataset",
        "vulnerability disclosure dataset",
        "NVD CVE feed dataset",
        "software vulnerability advisory dataset",
    ],
    "Governance, Risk and Compliance": [
        "security compliance controls dataset",
        "GRC risk register dataset",
        "NIST CSF mapping dataset",
        "ISO 27001 controls dataset",
        "security policy document dataset",
        "audit findings dataset cybersecurity",
        "control framework mapping dataset",
        "regulatory compliance dataset security",
    ],
    "Cryptography": [
        "cryptography dataset",
        "cipher cryptanalysis dataset",
        "TLS certificate dataset security",
        "encryption algorithms labeled dataset",
        "side channel attack dataset",
        "post-quantum cryptography dataset",
        "NIST PQC standard dataset",
        "lattice-based cryptography dataset",
        "key exchange protocol dataset",
        "crypto CTF challenge dataset",
    ],
    "Security Operations": [
        "SOC alert triage dataset",
        "SIEM log dataset",
        "security operations detection rules dataset",
        "threat hunting dataset",
        "Sigma rules dataset",
        "security alert labeled dataset",
        "log anomaly detection dataset",
        "EDR telemetry dataset",
    ],
    "Threat Intelligence": [
        "threat intelligence dataset",
        "IOC indicators of compromise dataset",
        "MITRE ATT&CK technique dataset",
        "phishing URL dataset",
        "APT report dataset",
        "malicious domain dataset",
        "malware family classification dataset",
        "YARA rules dataset",
        "malware API call sequence dataset",
        "threat actor TTP dataset",
        "CTI feed dataset",
    ],
}

# Prose-oriented catalog (mode "text"): articles, docs, tutorials, writeups.
DOMAIN_TEXT_KEYWORDS: dict[str, list[str]] = {
    "Application Security": [
        "OWASP top 10 explained",
        "secure coding best practices",
        "SQL injection prevention guide",
        "cross-site scripting XSS walkthrough",
        "threat modeling tutorial",
        "application security testing guide",
        "API security best practices",
        "common web vulnerabilities explained",
    ],
    "Network Security": [
        "network intrusion detection explained",
        "firewall configuration best practices",
        "DDoS mitigation guide",
        "network segmentation tutorial",
        "packet analysis with wireshark guide",
        "zero trust network architecture explained",
        "VPN security best practices",
        "network protocol attacks explained",
    ],
    "Cloud Security": [
        "AWS security best practices guide",
        "kubernetes security hardening tutorial",
        "cloud misconfiguration explained",
        "cloud IAM least privilege guide",
        "container security best practices",
        "cloud incident response guide",
        "securing S3 buckets tutorial",
        "cloud security posture management explained",
    ],
    "Identity Access and Management": [
        "identity and access management explained",
        "multi-factor authentication guide",
        "OAuth 2.0 explained",
        "SAML single sign-on tutorial",
        "privileged access management best practices",
        "zero trust identity guide",
        "RBAC vs ABAC explained",
        "preventing account takeover guide",
    ],
    "Incident Response and Forensics": [
        "incident response process explained",
        "digital forensics tutorial",
        "memory forensics with volatility guide",
        "DFIR investigation walkthrough",
        "malware incident handling guide",
        "windows event log analysis tutorial",
        "forensic artifact analysis explained",
        "ransomware incident response playbook",
    ],
    "Data Security and Privacy": [
        "data protection best practices",
        "GDPR compliance guide",
        "preventing data loss guide",
        "PII handling best practices",
        "data encryption at rest explained",
        "data classification tutorial",
        "privacy by design explained",
        "responding to a data breach guide",
    ],
    "Penetration Testing": [
        "penetration testing methodology guide",
        "exploit development tutorial",
        "red team operations guide",
        "web application pentest walkthrough",
        "privilege escalation techniques explained",
        "bug bounty writeup",
        "post-exploitation techniques explained",
        "lateral movement techniques guide",
    ],
    "Vulnerability Management": [
        "vulnerability management process explained",
        "CVSS scoring explained",
        "CVE and CWE explained",
        "patch management best practices",
        "vulnerability disclosure process explained",
        "risk-based vulnerability prioritization guide",
        "vulnerability scanning tools compared",
        "remediation SLA best practices",
    ],
    "Governance, Risk and Compliance": [
        "cybersecurity risk management guide",
        "NIST cybersecurity framework explained",
        "ISO 27001 implementation guide",
        "security policy writing best practices",
        "governance risk compliance explained",
        "security audit checklist",
        "third party risk management guide",
        "compliance frameworks compared",
    ],
    "Cryptography": [
        "cryptography explained",
        "how TLS works explained",
        "public key cryptography tutorial",
        "AES encryption explained",
        "digital signatures explained",
        "post-quantum cryptography explained",
        "NIST post-quantum standards guide",
        "migrating to quantum-safe cryptography guide",
        "common cryptographic attacks explained",
        "key management best practices",
    ],
    "Security Operations": [
        "security operations center explained",
        "SIEM best practices guide",
        "threat hunting guide",
        "writing detection rules tutorial",
        "alert triage process explained",
        "MITRE ATT&CK for detection guide",
        "SOC analyst workflow explained",
        "incident escalation best practices",
    ],
    "Threat Intelligence": [
        "cyber threat intelligence explained",
        "MITRE ATT&CK explained",
        "indicators of compromise guide",
        "threat actor profiling explained",
        "phishing analysis writeup",
        "malware analysis tutorial",
        "reverse engineering malware tutorial",
        "YARA rule writing guide",
        "APT campaign analysis",
        "threat intelligence lifecycle explained",
        "OSINT for threat intelligence guide",
    ],
}

# Distinctive terms per domain, used only to break ties on ambiguous results.
DOMAIN_VOCAB: dict[str, set[str]] = {
    "Application Security": {"sast", "owasp", "code", "sql injection", "xss",
                             "vulnerable code", "appsec", "source code"},
    "Network Security": {"intrusion", "ids", "pcap", "netflow", "ddos",
                         "packet", "traffic", "firewall"},
    "Cloud Security": {"cloud", "kubernetes", "aws", "azure", "gcp", "cspm",
                       "container", "s3 bucket", "misconfiguration"},
    "Identity Access and Management": {"iam", "identity", "authentication",
                                       "oauth", "saml", "privileged", "rbac"},
    "Incident Response and Forensics": {"forensics", "incident response",
                                        "dfir", "memory dump", "triage",
                                        "investigation", "artifact"},
    "Data Security and Privacy": {"pii", "privacy", "dlp", "gdpr",
                                  "sensitive data", "anonymization"},
    "Penetration Testing": {
        "penetration", "pentest", "exploit", "proof of concept", "poc",
        "metasploit", "red team", "privilege escalation", "payload"},
    "Vulnerability Management": {
        "vulnerability management", "cve", "cvss", "cwe", "nvd",
        "patch", "scan", "remediation", "disclosure"},
    "Governance, Risk and Compliance": {"compliance", "grc", "nist", "iso 27001",
                                        "controls", "audit", "risk register",
                                        "policy"},
    "Cryptography": {"cryptography", "cipher", "cryptanalysis", "encryption",
                     "tls", "certificate", "hash", "rsa", "aes",
                     "post-quantum", "pqc", "lattice", "kyber", "dilithium",
                     "ml-kem", "quantum-safe", "quantum-resistant"},
    "Security Operations": {"soc", "siem", "alert", "detection rule", "sigma",
                            "threat hunting", "triage"},
    "Threat Intelligence": {"threat intelligence", "ioc", "indicator",
                            "mitre att&ck", "phishing", "apt", "campaign",
                            "malware", "ransomware", "trojan", "yara",
                            "malware family"},
}

# mode name -> (keyword catalog, query qualifier)
_KEYWORD_SETS = {
    "datasets": (DOMAIN_KEYWORDS, QUERY_QUALIFIER),
    "text": (DOMAIN_TEXT_KEYWORDS, TEXT_QUERY_QUALIFIER),
}
MODES: tuple[str, ...] = ("datasets", "text", "both")


def keyword_sets(mode: str = "datasets") -> list[tuple[dict[str, list[str]], str]]:
    if mode == "both":
        return [_KEYWORD_SETS["datasets"], _KEYWORD_SETS["text"]]
    if mode in _KEYWORD_SETS:
        return [_KEYWORD_SETS[mode]]
    raise ValueError(f"unknown mode {mode!r}; valid: {MODES}")


# Canonical Sub-Domain labels (shared by both catalogs), exposed for CLI validation.
DOMAINS: tuple[str, ...] = tuple(DOMAIN_KEYWORDS)
