#!/usr/bin/env python3
"""Synthetic-source suggester - a curation aid (propose-only by default).

Scans each catalog row's Name / Description / Category / License for keywords
that suggest the source is model-generated, fabricated, or simulated, and reports
a suggested ``Is Synthetic?`` value plus the matched terms. It never decides on
its own: ``--apply`` writes only *high-confidence* suggestions, and weak
("review") matches are always left for a human.

A keyword scan only catches sources that *self-describe*. LLM-generated sets with
an innocuous description are missed, and rows flagged by inspecting the data (no
keyword) show up as "disagreements" - expected. Use it as a safety net over new /
crawler-added rows, not as the authority (that stays the ``Is Synthetic?`` flag).

Public API:
    classify_text(text)      -> (suggested, confidence, matched_terms)
    scan(spec=None)          -> list[dict]              # one result per source
    run_scan(spec=None, apply=False) -> dict            # report (+ optional write)
"""

from __future__ import annotations

import csv as _csv
import os
import re

from ..core import LOGS, logger
from ..ingestion.sources import (
    CATALOG_COLUMNS,
    DEFAULT_CATALOG,
    _bool,
    _norm_headers,
    _resolve,
    _val,
)

# Strong terms: a source that says any of these is almost certainly synthetic.
STRONG_TERMS = (
    "synthetic", "fabricated", "simulated", "simulation",
    "generated by", "llm-generated", "llm generated",
    "gpt-generated", "gpt generated", "ai-generated", "ai generated",
    "auto-generated", "auto generated", "machine-generated", "machine generated",
    "instruction-tuning", "instruction tuning", "instruct dataset", "dpo",
)
# Weak terms: suggestive but common in real data too -> "review", never auto-applied.
WEAK_TERMS = (
    "generated", "instruction", "instructions", "q&a", "q & a",
    "question-answer", "question and answer", "questions and answers",
    "prompt-response", "prompt/response", "prompt response",
    "augmented", "preference pairs",
)

REPORT = os.path.join(LOGS, "synthetic_scan.csv")
_REPORT_COLS = ("name", "dataset_link", "current", "suggested", "confidence", "matched")


def _matches(text: str, terms) -> list[str]:
    """Terms present in `text` as whole words/phrases (case handled by caller)."""
    return [t for t in terms if re.search(r"\b" + re.escape(t) + r"\b", text)]


def classify_text(text: str) -> tuple[str, str, list[str]]:
    """``(suggested, confidence, matched_terms)`` for free text.

    ``suggested`` is ``'Yes'`` (a strong term), ``'review'`` (weak term only), or
    ``'No'``. Strong beats weak; only strong is high-confidence.
    """
    low = (text or "").lower()
    strong = _matches(low, STRONG_TERMS)
    if strong:
        return "Yes", "high", strong
    weak = _matches(low, WEAK_TERMS)
    if weak:
        return "review", "low", weak
    return "No", "", []


def scan(spec: str | None = None) -> list[dict]:
    """Classify every catalog row against the keyword lists (read-only)."""
    import pandas as pd

    path = _resolve(spec or DEFAULT_CATALOG)
    df = _norm_headers(pd.read_csv(path, dtype=str, keep_default_na=False,
                                   encoding="utf-8"))
    rows: list[dict] = []
    for row in df.to_dict("records"):
        text = " ".join(filter(None, (
            _val(row, "name", default=""),
            _val(row, "description", default=""),
            _val(row, "category", default=""),
            _val(row, "license", default=""),
        )))
        suggested, conf, matched = classify_text(text)
        current = _bool(_val(row, "is_synthetic?", "is_synthetic"))
        rows.append({
            "name": _val(row, "name", default=""),
            "dataset_link": _val(row, "dataset_link", "url", "link", default=""),
            "current": "Yes" if current else "",
            "suggested": suggested,
            "confidence": conf,
            "matched": ", ".join(matched),
            # a high-confidence source the human hasn't flagged yet
            "gap": suggested == "Yes" and not current,
            # flagged by hand but keywords don't confirm it (e.g. data-sampled)
            "disagreement": current and suggested != "Yes",
        })
    return rows


def apply_suggestions(spec: str | None, rows: list[dict]) -> list[str]:
    """Write ``Is Synthetic? = Yes`` for high-confidence gaps; return changed Names.

    Only rows flagged ``gap`` (suggested ``Yes`` and not already marked) are
    written - ``review`` rows are never auto-applied. Idempotent.
    """
    import pandas as pd

    path = _resolve(spec or DEFAULT_CATALOG)
    targets = {r["dataset_link"] for r in rows if r["gap"]}
    if not targets:
        return []
    df = pd.read_csv(path, dtype=str, keep_default_na=False, encoding="utf-8")
    if "Is Synthetic?" not in df.columns:
        df["Is Synthetic?"] = ""
    changed: list[str] = []
    for i, link in enumerate(df["Dataset Link"]):
        if str(link).strip() in targets:
            df.at[i, "Is Synthetic?"] = "Yes"
            changed.append(str(df.at[i, "Name"]))
    df = df[[c for c in CATALOG_COLUMNS if c in df.columns]]
    df.to_csv(path, index=False, encoding="utf-8")
    return changed


def _write_report(rows: list[dict]) -> str:
    os.makedirs(LOGS, exist_ok=True)
    with open(REPORT, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=_REPORT_COLS)
        w.writeheader()
        for r in rows:
            w.writerow({k: r[k] for k in _REPORT_COLS})
    return REPORT


def run_scan(spec: str | None = None, *, apply: bool = False) -> dict:
    """Scan the catalog, print the report (+ write the CSV), optionally apply."""
    rows = scan(spec)
    gaps = [r for r in rows if r["gap"]]
    disagreements = [r for r in rows if r["disagreement"]]
    n_yes = sum(1 for r in rows if r["suggested"] == "Yes")
    n_review = sum(1 for r in rows if r["suggested"] == "review")
    n_flagged = sum(1 for r in rows if r["current"])
    _write_report(rows)

    print(f"synthetic-scan: {len(rows)} sources | suggested Yes={n_yes} "
          f"review={n_review} | currently flagged={n_flagged}")
    print(f"\nGAPS ({len(gaps)}) - high-confidence synthetic, NOT flagged:")
    for r in gaps or [{"name": "(none)", "matched": "", "dataset_link": ""}]:
        print(f"  + {r['name'][:30]:<30} [{r['matched']}]  {r['dataset_link']}")
    print(f"\nREVIEW - weak signal, decide by hand: "
          f"{n_review} rows (see {os.path.basename(REPORT)})")
    print(f"\nDISAGREEMENTS ({len(disagreements)}) - flagged but no keyword "
          f"(e.g. judged by sampling the data):")
    for r in disagreements or [{"name": "(none)", "suggested": "", "dataset_link": ""}]:
        print(f"  ? {r['name'][:30]:<30} scanner={r['suggested']:<6}  {r['dataset_link']}")
    print(f"\nreport -> {REPORT}")

    applied: list[str] = []
    if apply:
        applied = apply_suggestions(spec, rows)
        msg = (f"applied Is Synthetic?=Yes to {len(applied)}: {', '.join(applied)}"
               if applied else "--apply: no high-confidence gaps to write")
        logger.info(msg)
        print(f"\n{msg}")
    elif gaps:
        print("\n(propose-only - re-run with --apply to write the GAP rows above)")

    return {"total": len(rows), "suggested_yes": n_yes, "review": n_review,
            "gaps": len(gaps), "disagreements": len(disagreements),
            "applied": applied, "report": REPORT}
