#!/usr/bin/env python3
"""The ``cybersec`` profile: the original 12-domain cybersecurity taxonomy.

Lifted verbatim from the pre-profile ``sourcing/keywords.py`` so this profile's
discovery behaviour is byte-identical to what it was before profiles existed.
The enum codes in ``codes`` are the historical ones the downstream snorkel
LabelModel keys on and must not be renumbered while records carrying them exist.
"""

from __future__ import annotations

from . import Taxonomy

_DATASETS: dict[str, list[str]] = {'Application Security': ['vulnerable source code dataset',
                          'secure code review dataset',
                          'SAST static analysis labeled dataset',
                          'OWASP code vulnerability dataset',
                          'CWE annotated source code dataset',
                          'software vulnerability commit dataset',
                          'web application attack payload dataset',
                          'code security bug dataset github',
                          'vulnerability detection machine learning dataset',
                          'Devign vulnerability dataset',
                          'Juliet test suite CWE dataset',
                          'smart contract vulnerability dataset',
                          'fuzzing corpus github',
                          'SQL injection payload dataset',
                          'software supply chain security dataset',
                          'awesome application security'],
 'Network Security': ['network intrusion detection dataset',
                      'network traffic pcap labeled dataset',
                      'IDS flow dataset cybersecurity',
                      'DDoS attack network dataset',
                      'botnet traffic dataset',
                      'NetFlow anomaly detection dataset',
                      'packet capture malware traffic dataset',
                      'firewall log dataset',
                      'CICIDS intrusion detection dataset',
                      'UNSW-NB15 network dataset',
                      'network anomaly detection github',
                      'Zeek Suricata logs dataset',
                      'malware traffic analysis dataset',
                      'IoT network attack dataset',
                      'awesome network security'],
 'Cloud Security': ['cloud security misconfiguration dataset',
                    'kubernetes security dataset',
                    'cloud CSPM findings dataset',
                    'AWS Azure GCP security best practices dataset',
                    'container image vulnerability dataset',
                    'cloud audit log dataset security',
                    'terraform IaC misconfiguration dataset',
                    'S3 bucket exposure dataset',
                    'kubernetes audit logs dataset',
                    'cloudtrail logs dataset',
                    'falco runtime security rules github',
                    'IaC security scanning dataset',
                    'cloud attack detection dataset',
                    'serverless security dataset',
                    'awesome cloud security'],
 'Identity Access and Management': ['identity access management dataset',
                                    'authentication logs dataset security',
                                    'privileged access abuse dataset',
                                    'IAM policy misconfiguration dataset',
                                    'account takeover dataset',
                                    'OAuth SAML token dataset',
                                    'insider threat access dataset',
                                    'RBAC permissions dataset',
                                    'authentication anomaly detection dataset',
                                    'login logs dataset github',
                                    'user behavior analytics dataset security',
                                    'access control policy dataset',
                                    'SSO federation dataset',
                                    'credential stuffing dataset',
                                    'awesome iam security'],
 'Incident Response and Forensics': ['digital forensics dataset',
                                     'incident response playbook dataset',
                                     'memory forensics dataset',
                                     'DFIR investigation dataset',
                                     'disk image forensic dataset',
                                     'Windows event log forensic dataset',
                                     'timeline analysis artifact dataset',
                                     'malware incident case dataset',
                                     'volatility memory samples dataset',
                                     'windows forensic artifacts dataset',
                                     'log2timeline plaso dataset',
                                     'ransomware incident dataset github',
                                     'sysmon event dataset',
                                     'host intrusion detection dataset',
                                     'awesome incident response'],
 'Data Security and Privacy': ['PII detection dataset',
                               'data loss prevention dataset',
                               'data privacy compliance dataset',
                               'sensitive data classification dataset',
                               'GDPR data subject dataset',
                               'de-identification anonymization dataset',
                               'data breach records dataset',
                               'credential leak dataset',
                               'named entity PII dataset',
                               'text anonymization benchmark dataset',
                               'differential privacy dataset',
                               'synthetic PII dataset github',
                               'sensitive data detection github',
                               'data masking dataset',
                               'awesome data privacy'],
 'Penetration Testing': ['penetration testing dataset',
                         'exploit proof of concept dataset',
                         'exploit database github',
                         'red team TTP dataset',
                         'web pentest report dataset',
                         'privilege escalation technique dataset',
                         'attack payload dataset',
                         'CTF exploit writeup dataset',
                         'nuclei templates github',
                         'metasploit modules github',
                         'web attack payloads github',
                         'OSCP privilege escalation writeup',
                         'web application pentest dataset',
                         'bug bounty writeups github',
                         'awesome pentest'],
 'Vulnerability Management': ['CVE vulnerability dataset',
                              'CVSS scoring dataset',
                              'vulnerability scan results dataset',
                              'CWE weakness enumeration dataset',
                              'patch management dataset',
                              'vulnerability disclosure dataset',
                              'NVD CVE feed dataset',
                              'software vulnerability advisory dataset',
                              'CVE json feed github',
                              'exploit prediction EPSS dataset',
                              'dependency vulnerability dataset',
                              'OSV vulnerability database github',
                              'security advisories dataset',
                              'vulnerability scanner results dataset',
                              'awesome vulnerability management'],
 'Governance, Risk and Compliance': ['security compliance controls dataset',
                                     'GRC risk register dataset',
                                     'NIST CSF mapping dataset',
                                     'ISO 27001 controls dataset',
                                     'security policy document dataset',
                                     'audit findings dataset cybersecurity',
                                     'control framework mapping dataset',
                                     'regulatory compliance dataset security',
                                     'OSCAL security controls github',
                                     'CIS benchmark dataset',
                                     'security controls catalog dataset',
                                     'compliance mapping github',
                                     'risk assessment dataset github',
                                     'NIST 800-53 controls dataset',
                                     'awesome grc'],
 'Cryptography': ['cryptography dataset',
                  'cipher cryptanalysis dataset',
                  'TLS certificate dataset security',
                  'encryption algorithms labeled dataset',
                  'side channel attack dataset',
                  'post-quantum cryptography dataset',
                  'NIST PQC standard dataset',
                  'lattice-based cryptography dataset',
                  'key exchange protocol dataset',
                  'crypto CTF challenge dataset',
                  'cryptographic protocol dataset',
                  'TLS handshake dataset',
                  'hash function analysis dataset',
                  'homomorphic encryption dataset',
                  'awesome cryptography'],
 'Security Operations': ['SOC alert triage dataset',
                         'SIEM log dataset',
                         'security operations detection rules dataset',
                         'threat hunting dataset',
                         'Sigma rules dataset',
                         'security alert labeled dataset',
                         'log anomaly detection dataset',
                         'EDR telemetry dataset',
                         'sigma rules github',
                         'detection rules dataset github',
                         'MITRE ATT&CK detection dataset',
                         'SOC log dataset github',
                         'security alerts labeled dataset',
                         'detection engineering dataset',
                         'awesome detection engineering'],
 'Threat Intelligence': ['threat intelligence dataset',
                         'IOC indicators of compromise dataset',
                         'MITRE ATT&CK technique dataset',
                         'phishing URL dataset',
                         'APT report dataset',
                         'malicious domain dataset',
                         'malware family classification dataset',
                         'YARA rules dataset',
                         'malware API call sequence dataset',
                         'threat actor TTP dataset',
                         'CTI feed dataset',
                         'malware samples dataset github',
                         'phishing email dataset github',
                         'threat intelligence feeds github',
                         'ransomware samples dataset']}

_TEXT: dict[str, list[str]] = {'Application Security': ['OWASP top 10 explained',
                          'secure coding best practices',
                          'SQL injection prevention guide',
                          'cross-site scripting XSS walkthrough',
                          'threat modeling tutorial',
                          'application security testing guide',
                          'API security best practices',
                          'common web vulnerabilities explained'],
 'Network Security': ['network intrusion detection explained',
                      'firewall configuration best practices',
                      'DDoS mitigation guide',
                      'network segmentation tutorial',
                      'packet analysis with wireshark guide',
                      'zero trust network architecture explained',
                      'VPN security best practices',
                      'network protocol attacks explained'],
 'Cloud Security': ['AWS security best practices guide',
                    'kubernetes security hardening tutorial',
                    'cloud misconfiguration explained',
                    'cloud IAM least privilege guide',
                    'container security best practices',
                    'cloud incident response guide',
                    'securing S3 buckets tutorial',
                    'cloud security posture management explained'],
 'Identity Access and Management': ['identity and access management explained',
                                    'multi-factor authentication guide',
                                    'OAuth 2.0 explained',
                                    'SAML single sign-on tutorial',
                                    'privileged access management best practices',
                                    'zero trust identity guide',
                                    'RBAC vs ABAC explained',
                                    'preventing account takeover guide'],
 'Incident Response and Forensics': ['incident response process explained',
                                     'digital forensics tutorial',
                                     'memory forensics with volatility guide',
                                     'DFIR investigation walkthrough',
                                     'malware incident handling guide',
                                     'windows event log analysis tutorial',
                                     'forensic artifact analysis explained',
                                     'ransomware incident response playbook'],
 'Data Security and Privacy': ['data protection best practices',
                               'GDPR compliance guide',
                               'preventing data loss guide',
                               'PII handling best practices',
                               'data encryption at rest explained',
                               'data classification tutorial',
                               'privacy by design explained',
                               'responding to a data breach guide'],
 'Penetration Testing': ['penetration testing methodology guide',
                         'exploit development tutorial',
                         'red team operations guide',
                         'web application pentest walkthrough',
                         'privilege escalation techniques explained',
                         'bug bounty writeup',
                         'post-exploitation techniques explained',
                         'lateral movement techniques guide'],
 'Vulnerability Management': ['vulnerability management process explained',
                              'CVSS scoring explained',
                              'CVE and CWE explained',
                              'patch management best practices',
                              'vulnerability disclosure process explained',
                              'risk-based vulnerability prioritization guide',
                              'vulnerability scanning tools compared',
                              'remediation SLA best practices'],
 'Governance, Risk and Compliance': ['cybersecurity risk management guide',
                                     'NIST cybersecurity framework explained',
                                     'ISO 27001 implementation guide',
                                     'security policy writing best practices',
                                     'governance risk compliance explained',
                                     'security audit checklist',
                                     'third party risk management guide',
                                     'compliance frameworks compared'],
 'Cryptography': ['cryptography explained',
                  'how TLS works explained',
                  'public key cryptography tutorial',
                  'AES encryption explained',
                  'digital signatures explained',
                  'post-quantum cryptography explained',
                  'NIST post-quantum standards guide',
                  'migrating to quantum-safe cryptography guide',
                  'common cryptographic attacks explained',
                  'key management best practices'],
 'Security Operations': ['security operations center explained',
                         'SIEM best practices guide',
                         'threat hunting guide',
                         'writing detection rules tutorial',
                         'alert triage process explained',
                         'MITRE ATT&CK for detection guide',
                         'SOC analyst workflow explained',
                         'incident escalation best practices'],
 'Threat Intelligence': ['cyber threat intelligence explained',
                         'MITRE ATT&CK explained',
                         'indicators of compromise guide',
                         'threat actor profiling explained',
                         'phishing analysis writeup',
                         'malware analysis tutorial',
                         'reverse engineering malware tutorial',
                         'YARA rule writing guide',
                         'APT campaign analysis',
                         'threat intelligence lifecycle explained',
                         'OSINT for threat intelligence guide']}

_VOCAB: dict[str, set[str]] = {'Application Security': {'appsec',
                          'code',
                          'owasp',
                          'sast',
                          'source code',
                          'sql injection',
                          'vulnerable code',
                          'xss'},
 'Network Security': {'ddos',
                      'firewall',
                      'ids',
                      'intrusion',
                      'netflow',
                      'packet',
                      'pcap',
                      'traffic'},
 'Cloud Security': {'aws',
                    'azure',
                    'cloud',
                    'container',
                    'cspm',
                    'gcp',
                    'kubernetes',
                    'misconfiguration',
                    's3 bucket'},
 'Identity Access and Management': {'authentication',
                                    'iam',
                                    'identity',
                                    'oauth',
                                    'privileged',
                                    'rbac',
                                    'saml'},
 'Incident Response and Forensics': {'artifact',
                                     'dfir',
                                     'forensics',
                                     'incident response',
                                     'investigation',
                                     'memory dump',
                                     'triage'},
 'Data Security and Privacy': {'anonymization',
                               'dlp',
                               'gdpr',
                               'pii',
                               'privacy',
                               'sensitive data'},
 'Penetration Testing': {'exploit',
                         'metasploit',
                         'payload',
                         'penetration',
                         'pentest',
                         'poc',
                         'privilege escalation',
                         'proof of concept',
                         'red team'},
 'Vulnerability Management': {'cve',
                              'cvss',
                              'cwe',
                              'disclosure',
                              'nvd',
                              'patch',
                              'remediation',
                              'scan',
                              'vulnerability management'},
 'Governance, Risk and Compliance': {'audit',
                                     'compliance',
                                     'controls',
                                     'grc',
                                     'iso 27001',
                                     'nist',
                                     'policy',
                                     'risk register'},
 'Cryptography': {'aes',
                  'certificate',
                  'cipher',
                  'cryptanalysis',
                  'cryptography',
                  'dilithium',
                  'encryption',
                  'hash',
                  'kyber',
                  'lattice',
                  'ml-kem',
                  'post-quantum',
                  'pqc',
                  'quantum-resistant',
                  'quantum-safe',
                  'rsa',
                  'tls'},
 'Security Operations': {'alert',
                         'detection rule',
                         'siem',
                         'sigma',
                         'soc',
                         'threat hunting',
                         'triage'},
 'Threat Intelligence': {'apt',
                         'campaign',
                         'indicator',
                         'ioc',
                         'malware',
                         'malware family',
                         'mitre att&ck',
                         'phishing',
                         'ransomware',
                         'threat intelligence',
                         'trojan',
                         'yara'}}

_CODES: dict[str, str] = {'Application Security': 'APPLICATION',
 'Cloud Security': 'CLOUD',
 'Cryptography': 'CRYPTOGRAPHY',
 'Data Security and Privacy': 'DATA_PRIVACY',
 'Governance, Risk and Compliance': 'GRC',
 'Identity Access and Management': 'IAM',
 'Incident Response and Forensics': 'INCIDENT_RESPONSE',
 'Network Security': 'NETWORK',
 'Penetration Testing': 'PENTEST',
 'Security Operations': 'SECOPS',
 'Threat Intelligence': 'THREAT_INTELLIGENCE',
 'Vulnerability Management': 'VULN_MANAGEMENT'}

TAXONOMY = Taxonomy(
    domain_name='CYBERSEC',
    datasets=_DATASETS,
    text=_TEXT,
    vocab=_VOCAB,
    codes=_CODES,
    site_scope_hosts=(
        'huggingface.co', 'github.com', 'gitlab.com', 'kaggle.com',
        'zenodo.org', 'arxiv.org', 'data.gov', 'archive.ics.uci.edu',
    ),
    dataset_engines=('github', 'openairedatasets', 'arxiv', 'semantic scholar'),
    text_engines=('github', 'stackoverflow', 'arxiv', 'semantic scholar'),
    query_qualifier='dataset OR github OR repository OR corpus',
    text_query_qualifier='guide OR tutorial OR explained OR documentation OR writeup',
    # The cybersecurity corpus draws on open dataset hosts only; no on-topic host
    # needed a licensing bar, so discovery relies on the license gate alone.
    restricted_hosts={},
)
